package apperror

var (
	ErrPanicDefault            = New(10000, "Default panic error", nil)
	ErrInvalidParameters       = New(10001, "Invalid parameters", nil)
	ErrUnauthenticated         = New(10002, "Unauthenticated access", nil)
	ErrForbidden               = New(10003, "Unauthorized access", nil)
	ErrNotFound                = New(10004, "Not found", nil)
	ErrTimeout                 = New(10005, "Timeout", nil)
	ErrSerialNotFound          = New(10006, "Serial not found", nil)
	ErrAccountNotFound         = New(10007, "Owner account not found", nil)
	ErrRegisteredSerial        = New(10008, "Serial already registered", nil)
	ErrNotReady                = New(10009, "Service not ready", nil)
	ErrPermissionRequired      = New(10010, "Access permission required", nil)
	ErrInternal                = New(10011, "Internal service exception", nil)
	ErrExisted                 = New(10012, "Item already existed", nil)
	ErrEndUserPermission       = New(10013, "This is UserDefault, can not delete or modify", nil)
	ErrGroupEndUserPermission  = New(10014, "This is GroupDefault, can not delete or modify", nil)
	ErrScenarioPermission      = New(10015, "This is ScenarioDefault or scenario applied, can not delete or modify", nil)
	ErrPolicyPermission        = New(10016, "This is PolicyDefault, can not delete or modify", nil)
	ErrUnrecognized            = New(10017, "unrecognized data", nil)
	ErrNotImplemented          = New(10018, "this feature has not been implemented yet", nil)
	ErrRateLimitExceeded       = New(10019, "rate limit exceeded", nil)
	ErrNotMatched              = New(10020, "data not matched", nil)
	ErrTryAgainLater           = New(10021, "should try again later", nil)
	ErrEdgeNotFound            = New(10022, "Edge not found", nil)
	ErrUnsupportedDataType     = New(10023, "Unsupported data type", nil)
	ErrConstraintViolation     = New(10024, "Some constraints violated", nil)
	ErrOtpInvalid              = New(10025, "Otp is invalid", nil)
	ErrNumberLimitExceeded     = New(10026, "Number limit exceeded", nil)
	ErrEmailVerified           = New(10027, "Email already verified", nil)
	ErrValidateOtp             = New(10028, "You must login first", nil)
	ErrUrlInvalid              = New(10029, "Url is invalid", nil)
	ErrEdgeModelInvalid        = New(10030, "Edge model invalid", nil)
	ErrFirmwareVersionNotFound = New(10031, "Not found firmware version", nil)
	ErrPhoneNumberVerified     = New(10032, "Phone number already verified", nil)
	ErrPhoneNumberNotVerify    = New(10033, "Phone number not verify", nil)
	ErrNumberLimitSendOtp      = New(10034, "Try again after 7 days, because you have exceeded the otp sending limit", nil)
	ErrSignatureNotVerify      = New(10035, "Signature not verify", nil)
	ErrExpiredCert             = New(10036, "Certificate has expired", nil)
	ErrInvalidCert             = New(10037, "Certificate invalid", nil)
	ErrSendSmsFailed           = New(10037, "Send SMS failed", nil)
)
