database:
  postgresql:
    connection-string: "postgres://lancs:lancs@192.168.1.174:8080/linksafe?sslmode=disable"

security:
  auth:
    jwt:
      alg: HS256
      base64-secret: OU9MV3hORDRvODNqNEs0aXVvcE85T0xXeE5ENG84M2o0SzRpdW9wTw==

services:
  wazuh:
    esUser: elastic
    esPassword: 8PwH5rEks9km4e0saMTZ
    indexer: https://192.168.1.33:9200
    wazuhPassword: lancs-wui