// Code generated by ifacemaker; DO NOT EDIT.

package spec

import (
	"github.com/gin-gonic/gin"
)

// IEdgeControlHandler ...
type IRetailsController interface {
	CustomerOrderStatus(c *gin.Context)
}

